### ISSUE TITLE
PDF() uses Julia Mono but there's no installation suggestion

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaBooks/Books.jl#254]
I tied to run `pdf()` but it errors with: 

```Julia
error: texput.tex:46: Package fontspec Error: The font "JuliaMono-Regular" cannot be found.

For immediate help type H <return>
error: halted on potentially-recoverable error as specified
Error producing PDF.
! Package fontspec Error: The font "JuliaMono-Regular" cannot be found.

```

However, the docs: https://books.huijzer.xyz/getting-started mention nothing about adding the font.

**Comment by logankilpatrick** [comment]
It's also unclear to me where this is being set and how I would override it

**Comment by logankilpatrick** [comment]
I see a mention here: https://books.huijzer.xyz/other-notes but no note on how to override it

**Comment by logankilpatrick** [comment]
Adding via home-brew fixes the issue but should be setup as a dep: https://juliamono.netlify.app/download/#installation

**Comment by rikhuijzer** [comment]
Yes, this is a very good point. I have a solution in my head already, but didn't implement it yet. In essence, I should just pass the Julia Artifacts link to the PDF template just like `listings_path` is also passed into the template.

**Comment by rikhuijzer** [comment]
> Adding via home-brew fixes the issue but should be setup as a dep: https://juliamono.netlify.app/download/#installation

It would probably be better if it is not a dep but an artifact via Artifacts. That's platform independent.
