### ISSUE TITLE
Add new Books.jl org logo

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaBooks/Books.jl#259]
![Books jl - Logo](https://user-images.githubusercontent.com/35577566/143054917-b8cd0478-8089-46c7-9943-5af3e439dc5b.png)

**Comment by rikhuijzer** [comment]
Can I get a bit more context? How is this image created? What license does it have? Where should it be?

**Comment by logankilpatrick** [comment]
I created the image with Canva so we can use it however we would like. The main use of the logo would be for the JuliaBooks GitHub organization. You could also add it here: https://github.com/JuliaBooks/Books.jl/tree/main/docs/images if you want for easy access

**Comment by rikhuijzer** [comment]
And not for the favicon?

**Comment by logankilpatrick** [comment]
You could use it for that as well! 

Best, 
Logan Kilpatrick

**Comment by rikhuijzer** [comment]
The image of an unfolded book seems to be too detailed to be suitable for a favicon:

![image](https://user-images.githubusercontent.com/20724914/144853103-6d7f2c6e-b218-422e-9a06-ed809f143ea7.png)

I've changed the JuliaBooks org logo though because the image is nice for that
