### ISSUE TITLE
Use Yggdrasil tectonic?

### ISSUE THREAD

**Issue by jeremiahpslewis** [JuliaBooks/Books.jl#261]
Hey!

Looks like you have already explored this issue / problem space, so no worries if you just close this...but:

- tectonic 0.8.0 is now available in Yggdrasil (thanks to @giordano)
- Including support across Linux, Windows, Mac (and Apple Silicon)
- Rust Yggdrasil toolchain is now well maintained, so should be able to track with tectonic releases
- And we get broader binary support for typical Julia-supported platforms than is available directly from tectonic

...so would it make sense to switch (back) to using the `tectonic_jll` package?

Cheers,
Jeremiah

**Comment by rikhuijzer** [comment]
Thanks for the nudge. Yes, it probably would :smile:

I'm planning to do a focused day of Books.jl bug-fixing soon and I'll pick this issue up then.

**Comment by rikhuijzer** [comment]
On hold due to https://github.com/JuliaPackaging/Yggdrasil/issues/4046.
