### ISSUE TITLE
Why is the `CJKmainfont` related configurations removed from "template.tex"?

### ISSUE THREAD

**Issue by findmyway** [JuliaBooks/Books.jl#267]
At least it was there in Books@v0.4.4:

https://github.com/JuliaBooks/Books.jl/blob/a3eb9cee04f808140a2c4113814869824134be33/defaults/template.tex#L193-L209

But I'm not sure why it was removed later.

**Comment by rikhuijzer** [comment]
It wasn’t removed per se, I moved to another template which didn’t include it by default.

It can be added again if that would help your project. I’m currently away from keyboard though

**Comment by rikhuijzer** [comment]
On second thought, I removed it to make things simpler. I didn’t think it added much but apparently it does

**Comment by findmyway** [comment]
> On second thought, I removed it to make things simpler. I didn’t think it added much but apparently it does

I see. Just to make sure it is not removed by chance. I agree that most users would not need this config. And when they do, a customized template can be created.

**Comment by rikhuijzer** [comment]
Nice that’s it is solved then. Thanks for letting me know 👍
