### ISSUE TITLE
An Options method with AlgebraOfGraphics.FigureGrid as  the first argument

### ISSUE THREAD

**Issue by dmbates** [JuliaBooks/Books.jl#275]
I haven't taken things apart to discover what the sequence of operations for a call to `Options(...)` is, but it seems that in recent versions of `AlgebraOfGraphics` the type of object returned by `draw`, `AlgebraOfGraphics.FigureGrid`, is no longer recognized as an object to be plotted.  I needed to change from
```jl
Options(draw(...); caption="...", ...)
```
to
```jl
Options(draw(....).figure; caption="...", ...)
```

If you could give me a hint of where to look I would be willing to create a PR.

**Comment by rikhuijzer** [comment]
You can ignore that error. It is just a problem that `Requires.jl` hasn't solved yet. It should not introduce any problems.

So everything works if you use `draw(....).figure`?

**Comment by dmbates** [comment]
Thanks for checking.  Yes, it works if I use `draw(....).figure`.

**Comment by rikhuijzer** [comment]
It was able to reproduce your issue. I've now added `AlgebraOfGraphics.jl` to the `Project.toml` which solved the issue for me. Now, also passing `fg` works. Please let me know if that's not the case.

The drawback of adding `AlgebraOfGraphics.jl` to the `Project.toml` is that it gets installed for anyone who installs `Books.jl`. However, the package isn't too big so it's a fair tradeoff, especially if it solves problems. The error should now also be gone.

**Comment by dmbates** [comment]
Thanks for addressing this, Rik.  I should give you a heads-up that I have looking into [quarto](https://quarto.org) and have started converting our book to quarto format.  I have experience with R and Rmarkdown and the quarto system has a familiar feel to it.  I appreciate what you have done in Books.jl and the response that you have provided to us but I will probably go with quarto in the future.

**Comment by rikhuijzer** [comment]
> Thanks for addressing this, Rik. I should give you a heads-up that I have looking into [quarto](https://quarto.org) and have started converting our book to quarto format. I have experience with R and Rmarkdown and the quarto system has a familiar feel to it. I appreciate what you have done in Books.jl and the response that you have provided to us but I will probably go with quarto in the future.

Yeah sure no worries. Like I said on <https://books.huijzer.xyz/>, there are some fundamental problems with `Books.jl` which also cannot easily be solved. For my own projects, I do still use the package, but I'm also aware that it isn't super great.
