### ISSUE TITLE
Newline required for each content file?

### ISSUE THREAD

**Issue by henry2004y** [JuliaBooks/Books.jl#295]
Hi,

I am learning to use this wonderful package. While playing around I quickly had an issue about adding new markdown files and generating the table of contents. It turns that without a newline character at the end of each markdown file, Books.jl decide to append the files according to the ordering defined in `config.toml`, and generate a wrong TOC.

Is this a strict requirement for correctly parsing the files? If so, it may be good to mention it in the doc.

**Comment by rikhuijzer** [comment]
> Is this a strict requirement for correctly parsing the files? If so, it may be good to mention it in the doc.

Let's call it a bug. I was just yesterday thinking about that there are also some bugs where

    ```jl
    x = something()
    ```
    my text

gets an incorrect output whereas the following would be correct:

    ```jl
    x = something()
    ```

    my text
    
In all cases, it is Pandoc who has a bit of an interesting parser sometimes, but it can and should best be fixed at the `Books.jl` side. I'm leaving this issue open to track it and hopefully find some time to fix it

**Comment by rikhuijzer** [comment]
This should be fixed in `Books.jl` v2.0.2 which will be available in around 30 minutes. Could you test whether it fixes the issue?

**Comment by henry2004y** [comment]
I think it works: newlines are not needed. Thanks!
